CREATE TABLE T_POSTAGEM (
    POS_CODIGO BIGINT NOT NULL IDENTITY(1,1),
    POS_TEXTO NVARCHAR(4000),
    POS_IMAGEM NVARCHAR(MAX),
    POS_DATA_CRIACAO DATETIME NOT NULL,
    USU_CODIGO BIGINT NOT NULL,
    POS_CURTIDAS INTEGER NOT NULL,
    POS_COMENTARIOS INTEGER NOT NULL,

    PRIMARY KEY(POS_CODIGO),
    FOREIGN KEY (USU_CODIGO) REFERENCES T_USUARIO(USU_CODIGO)
);
