CREATE TABLE T_POSTAGEM_COMENTARIO (
    PCO_CODIGO BIGINT NOT NULL IDENTITY(1,1),
    POS_CODIGO BIGINT NOT NULL,
    USU_CODIGO BIGINT NOT NULL,
    PCO_DATA_CRIACAO DATETIME NOT NULL,
    PCO_TEXTO NVARCHAR(4000),
    PCO_FOTO NVARCHAR(MAX),
    PCO_CODIGO_PAI BIGINT,
    PCO_CURTIDAS INTEGER NOT NULL,
    PCO_RESPOSTAS INTEGER NOT NULL,

    PRIMARY KEY(PCO_CODIGO),
    FOREIGN KEY (POS_CODIGO) REFERENCES T_POSTAGEM(POS_CODIGO),
    FOREIGN KEY (USU_CODIGO) REFERENCES T_USUARIO(USU_CODIGO),
    FOREIGN KEY (PCO_CODIGO_PAI) REFERENCES T_POSTAGEM_COMENTARIO(PCO_CODIGO) 
);
