CREATE TABLE T_POSTAGEM_COMENTARIO_CURTIDA (
    PCC_CODIGO BIGINT NOT NULL IDENTITY(1,1),
    PCO_CODIGO BIGINT NOT NULL,
    USU_CODIGO BIGINT NOT NULL,

    PRIMARY KEY(PCC_CODIGO),
    FOREIGN KEY (PCO_CODIGO) REFERENCES T_POSTAGEM_COMENTARIO(PCO_CODIGO),
    FOREIGN KEY (USU_CODIGO) REFERENCES T_USUARIO(USU_CODIGO)
);
