CREATE TABLE T_USUARIO (
    USU_CODIGO BIGINT NOT NULL IDENTITY(1,1),
    USU_EMAIL NVARCHAR(255) NOT NULL UNIQUE,
    USU_SENHA NVARCHAR(255) NOT NULL,
    USU_EMAIL_CONFIRMADO BIT NOT NULL,
    USU_NOME NVARCHAR(100) NOT NULL,
    USU_FOTO NVARCHAR(MAX),
    USU_RESUMO NVARCHAR(255),
    USU_DATA_NASCIMENTO DATETIME NOT NULL,
    USU_LATITUDE DECIMAL(9,6),
    USU_LONGITUDE DECIMAL(9,6),

    PRIMARY KEY (USU_CODIGO)
);
