CREATE TABLE T_CONFIRMACAO_EMAIL (
    CEM_CODIGO BIGINT NOT NULL IDENTITY(1,1),
    USU_CODIGO BIGINT NOT NULL,
    CEM_CODIGO_CONFIRMACAO VARCHAR(6) NOT NULL,
    CEM_DATA_EXPIRACAO DATETIME NOT NULL,

    PRIMARY KEY(CEM_CODIGO),
    FOREIGN KEY (USU_CODIGO) REFERENCES T_USUARIO(USU_CODIGO)
);
