CREATE TABLE T_ESQUECIMENTO_SENHA (
    ESQ_CODIGO BIGINT NOT NULL IDENTITY(1,1),
    USU_CODIGO BIGINT NOT NULL,
    ESQ_CODIGO_CONFIRMACAO VARCHAR(6) NOT NULL,
    ESQ_DATA_EXPIRACAO DATETIME NOT NULL,
    ESQ_NOVA_SENHA NVARCHAR(255) NOT NULL,

    PRIMARY KEY(ESQ_CODIGO),
    FOREIGN KEY (USU_CODIGO) REFERENCES T_USUARIO(USU_CODIGO)
);
