CREATE TABLE T_AMIZADE (
    AMI_CODIGO BIGINT NOT NULL IDENTITY(1,1),
    USU_CODIGO_PRINCIPAL BIGINT NOT NULL,
    USU_CODIGO_AMIGO BIGINT NOT NULL,
    AMI_DATA DATETIME NOT NULL,

    PRIMARY KEY(AMI_CODIGO),
    FOREIGN KEY (USU_CODIGO_PRINCIPAL) REFERENCES T_USUARIO(USU_CODIGO),
    FOREIGN KEY (USU_CODIGO_AMIGO) REFERENCES T_USUARIO(USU_CODIGO)
);
