CREATE TABLE T_SOLICITACAO (
    SOL_CODIGO BIGINT NOT NULL IDENTITY(1,1),
    USU_CODIGO_REMETENTE BIGINT NOT NULL,
    USU_CODIGO_DESTINATARIO BIGINT NOT NULL,
    SOL_DATA DATETIME NOT NULL,

    PRIMARY KEY(SOL_CODIGO),
    FOREIGN KEY (USU_CODIGO_REMETENTE) REFERENCES T_USUARIO(USU_CODIGO),
    FOREIGN KEY (USU_CODIGO_DESTINATARIO) REFERENCES T_USUARIO(USU_CODIGO)
);
